CREATE OR REPLACE PROCEDURE HR.GET_EMPLOYEES_DETAIL(V_PATH_DEP  OUT VARCHAR2,
                                                    RES_DEP     OUT SYS_REFCURSOR,
                                                    V_PATH_EMP  OUT VARCHAR2,
                                                    RES_EMP_DEP OUT SYS_REFCURSOR)

 AS
BEGIN

  V_PATH_EMP := 'C:\Users\Reza\HR_FILES\EMP.xlsx';
  V_PATH_DEP := 'C:\Users\Reza\HR_FILES\DEP';

  OPEN RES_DEP FOR
    SELECT D.DEPARTMENT_ID,
           D.DEPARTMENT_NAME,
           C.COUNTRY_NAME,
           L.STATE_PROVINCE,
           L.STREET_ADDRESS,
           AVG(E.SALARY) AVG_SALARY
    
      FROM HR.DEPARTMENTS D
     INNER JOIN HR.LOCATIONS L
        ON L.LOCATION_ID = D.LOCATION_ID
     INNER JOIN HR.COUNTRIES C
        ON C.COUNTRY_ID = L.COUNTRY_ID
     INNER JOIN HR.EMPLOYEES E
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
     GROUP BY D.DEPARTMENT_ID,
              D.DEPARTMENT_NAME,
              C.COUNTRY_NAME,
              L.STATE_PROVINCE,
              L.STREET_ADDRESS
     ORDER BY 1;

  OPEN RES_EMP_DEP FOR
    SELECT E.EMPLOYEE_ID,
           E.FIRST_NAME || ' ' || E.LAST_NAME FULL_NAME,
           D.DEPARTMENT_NAME,
           EM.FIRST_NAME || ' ' || EM.LAST_NAME MANAGER_FULL_NAME
      FROM HR.EMPLOYEES E
     INNER JOIN HR.DEPARTMENTS D
        ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
     INNER JOIN HR.EMPLOYEES EM
        ON EM.EMPLOYEE_ID = E.MANAGER_ID
     ORDER BY 1;

END GET_EMPLOYEES_DETAIL;
